In [149]:
#1 Задание 1. Напишите программу (необходимые данные вводятся с клавиатуры) 
#для вычисления всех трёх сторон прямоугольного треугольника, если даны один из острых углов и площадь.
import math as mt
alpha=float(input())
s = float(input())
k1=np.sqrt((2*s)/np.tan(mt.radians(alpha)))
k2=np.sqrt((2*s)/np.tan(mt.radians(90-alpha)))
print('Катет b =',k1)
print('Катет a =',k2)
print('Гипотенуза =',np.sqrt((k1**2)+(k2**2)))

4
45
Катет b = 35.87561794734793
Катет a = 2.508667589561425
Гипотенуза = 35.963222549974425


In [9]:
#
x = float(input('Значение x '))
y = float(input('Значение y '))
if (x**3) + (y**3) <= 9:
    print("Истенно")
else:
    print("Ложно")

Значение x 2
Значение y 2
Ложно


In [15]:
x = int(input("Введите число:" ))
if (x % 2 == 0) and (x < 100):
    print("Истенно")
else:
    print("Ложно")

Введите число:110
Ложно


In [20]:
money = int(input("Деньги: "))
bread = 20
chees = 100
if money - bread - chees >= 0:
    print("Купли сыр и хлеб")
else:
    if money - chees >= 0:
        print("Купили сыр")
    elif money - bread >= 0:
        print("Купили хлеб")
    else:
        print("Ничего не купили")

Деньги: 19
Ничего не купили


In [136]:
# Задание 5
mini_bottle = int(input("Кол-во бутылок объемом 1 литр и меньше "))
maxi_bottle = int(input("Кол-во бутылок объемом больше 1 литра "))
counter = mini_bottle * 0.10 + maxi_bottle * 0.25
print("Ваша денюшка","%.2f" % counter,"$")

Кол-во бутылок объемом 1 литр и меньше 1
Кол-во бутылок объемом больше 1 литра 10
Ваша денюшка 2.60 $


In [137]:
bill = float(input("Сумма заказа: "))
nalog = bill * 0.2
pourboire = bill * 0.18
ostatok = bill - nalog - pourboire
print("Налог: ", "%.2f" % nalog, "Сумма чаевых: " "%.2f" % pourboire, "Итог: " "%.2f" % ostatok)

Сумма заказа: 20000
Налог:  4000.00 Сумма чаевых: 3600.00 Итог: 12400.00


In [12]:
suvenir = int(input("сувениров шт "))
bezdelyska = int(input("безделушек шт "))
ves = suvenir * 75 + bezdelyska * 112
print("Общий вес:", ves)

сувениров шт1
безделушек шт1
Общий вес: 187


In [16]:
# через while
deposit = int(input("Сумма первонач. депозита: "))
year = 0
while year != 3:
    year+= 1
    deposit = deposit + deposit * 0.04
    print("%.2f" % deposit, "Год", year)

Сумма первонач. депозита: 1000000
1040000.00 Год 1
1081600.00 Год 2
1124864.00 Год 3


In [19]:
# через for
deposit = int(input("Сумма первонач. депозита: "))
for i in range(3):
    deposit = deposit + deposit * 0.04
    print("%.2f" % deposit, "Год", i+1)

Сумма первонач. депозита: 1000000
1040000.00 Год 1
1081600.00 Год 2
1124864.00 Год 3


In [23]:
import math
a = int(input("Первое число: "))
b = int(input("Второе число: "))
print(a * b)
print(a - b)
print(a // b)
print(a % b)
print(math.log10(a))
print(a ** b)

Первое число: 10
Второе число: 2
20
8
5
0
1.0
100


In [ ]:
# Задание 10

In [24]:
foot = int(input("Рост, футы: ")) # Jajajajajaja
duim = int(input("Рост, дюймы: "))
foot_to_duim = foot * 12 + duim
duim_to_sm = foot_to_duim * 2.54
print("Ваш рост:", duim_to_sm,"см")

Рост, футы: 5
Рост, дюймы: 5
Ваш рост: 165.1 см


In [28]:
a = float(input("a: "))
h = float(input("h: "))
S = 0.5 * a * h
print(S, a, h)

a: 70
h: 10
350.0 70.0 10.0


In [146]:
x = input("Введите 4значное число: ")
l = [0, 0, 0, 0]
x_len = len(x)
for i in range(x_len):
    l[i] = int(x[i])
print(l[0], "+", l[1], "+", l[2], "+", l[3], "=", sum(l))

Введите 4значное число: 3141
3 + 1 + 4 + 1 = 9


In [35]:
# Задание 15
bread_q = int(input("Количество приобретенных вчерашних буханок хлеба: "))
price = 49
sale = 0.6
sale_price = price * sale
bread_cost = bread_q * price
bread_sale_coast = bread_q * sale_price 
print("Обычная цена за буханку:",price,"\nЦена со скидкой:", "%.2f" % sale_price,
      "\nОбщая стоимость приобретенного хлеба:", "%.2f" % bread_sale_coast)

Количество приобретенных вчерашних буханок хлеба: 2
Обычная цена за буханку: 49 
Цена со скидкой: 29.40 
Общая стоимость приобретенного хлеба: 58.80


In [ ]:
person_age = int(input("Ваш возраст: "))
person_age1 = person_age
dog_age = 0
if person_age >= 0:
    while person_age > 0:
        if dog_age < 2:
            person_age = person_age - 10.5
            dog_age+= 1
        else:
            person_age = person_age - 7
            dog_age+= 1
    print("Ваш возраст",person_age1,"=",dog_age,"годам собаки")
else:
    print("число должно быть положительным")

In [8]:
bukva = input("Буква: ")
spisok = list("aeiou")
if bukva != "y":
    if bukva in spisok:
        print("Гласная")
    else:
        print("Согласная")
else:
    print("буква может быть как гласной, так и согласной")

Буква: y
буква может быть как гласной, так и согласной


In [4]:
month_name = input("Введите месяц: ")
month31 = ["январь", "март", "май", "июль", "август", "октябрь", "декабрь"]
month30 = ["апрель", "июнь", "сентябрь", "ноябрь"]
month_febrari = ("февраль")
if month_name in month31:
    print("31")
elif month_name in month30:
    print("30")
elif month_name == month_febrari:
    print('28 or 29')
else:
    print("попробуйте ещё раз")

Введите месяц: ноябрь
30


In [7]:
a = int(input("A:"))
b = int(input("B:"))
c = int(input("C:"))
if a == b == c:
    print("Треугольник равносторонний")
elif a == b or b == c or a == c:
    print("Треугольник равнобедренный")
else:
    print("Треугольник разносторонний")

A:12
B:23
C:34
Треугольник разносторонний


In [5]:
# Задание 20
# 1 sposob
a = "У Лукоморья дуб зелёный"
print(a[::-1])
# 2 sposob
a = "У Лукоморья дуб зелёный"
l = []
l.extend(a)
l.reverse()
a = "".join(l)
print(a)

йынёлез буд яьромокуЛ У
йынёлез буд яьромокуЛ У


In [19]:
# без цикла
word = input("Word: ")
palindrom = word[::-1]
if word == palindrom:
    print("Слово палиндром")
else:
    print("Слово ne палиндром")

# цикл 
word = input("Word: ")
word_len = int(len(word))
word_len_cupl = word_len // 2
word_len = word_len - 1
l = []
l.extend(word)
for i in range(word_len_cupl):
    l[word_len - i], l[i] = l[i], l[word_len - i]
palindrom = "".join(l)
if word == palindrom:
    print("Слово палиндром")
else:
    print("Слово ne палиндром")

Word: test
Слово ne палиндром
Word: level
Слово палиндром


In [3]:
emails_list = ['vasya@mail.ru',
 'akakiy@yandex.ru',
 'spyderman@yandex.ru',
 'XFiles@gmail.com',
 'hello@mail.ru',
 'noname@gmail.com',
 'DonaldTrump@mail.ru',
 'a768#af@yandex.ru',
 'Ivan_Ivanovich@yandex.ru',
 'thebestmail@yandex.ru']

In [11]:
string = "без труда не вытащишь и рыбку из пруда"
print(string.title()) #.title()

Без Труда Не Вытащишь И Рыбку Из Пруда


In [69]:
string = 'Тяжёлая интернет-зависимость — это когда ты выходишь из интернета, а он из тебя нет.'
simvoli = "-—,."
cstring = len(string)
for i in range(cstring):
    if string[i] in simvoli:
        string[i] = 
print(string)

SyntaxError: invalid syntax (<ipython-input-69-3cbfc3218364>, line 6)

ValueError: 0 is not in list

In [27]:
# Задание 25
name = "Статистика"
glasnie = "аяоёуюиыэе"
cname = len(name)

for i in range(cname):
    if name[i] in glasnie:
        print(name[i],"- гласная буква")
    else:
        print(name[i], "- согласная буква")

С - согласная буква
т - согласная буква
а - гласная буква
т - согласная буква
и - гласная буква
с - согласная буква
т - согласная буква
и - гласная буква
к - согласная буква
а - гласная буква


In [34]:
string = input("Введите слово: ")
print(string[::-1])

Введите слово: милан
налим


In [54]:
def func(a,b):
    c = (a ** 2 + b ** 2) ** (1 / 2)
    print(c)

In [55]:
func(4, 3)

5.0


In [63]:
def route(x):
    in_m = x * 1000
    cost = 4 + (in_m // 140) * 0.25
    print(cost, "$")
route(1)

5.75 $


In [71]:
def delivery_cost(x):
    if x > 0:
        cost = 10.95 + (x - 1) * 2.95
        print("Стоимость доставки:", "%.2f" % cost)
    else:
        print("Неверный ввод")
delivery_cost(int(input("Введите кол-во товара: ")))

Введите кол-во товара: 3
Стоимость доставки: 16.85


In [88]:
d = {
    1: "one",
    2: "two",
    3: "free",
    4: "four",
    5: "five",
    6: "six",
    7: "seven",
    8: "eight",
    9: "nine",
    10: "ten",
    11: "eleven",
    12: "twelve",
}
def proga(x):
    print(d.setdefault(x))
proga(int(input("Введите число: ")))
proga(int(input("Введите число: ")))

Введите число: 9
nine
Введите число: 99
None


In [ ]:
# Задание 30

In [23]:
fruts_name = ["Яблоки", "Бананы", "Ананасы"]
fruts_count = [30, 21, 6]
l_fruts_name = {"Яблоки": [30], "Бананы": [21],"Ананасы": [6]}
fruits = pd.DataFrame(data=l_fruts_name)
fruits

Яблоки  Бананы  Ананасы
0      30      21        6

In [32]:
l_fruts_name = {"Яблоки": [35, 41, 47], "Бананы": [21, 34, 40]}
frut_year = ["2017 sales", "2018 sales", "2019 sales"]
fruit_sales = pd.DataFrame(data=l_fruts_name, index = frut_year)
fruit_sales

Яблоки  Бананы
2017 sales      35      21
2018 sales      41      34
2019 sales      47      40

In [1]:
import pandas as pd

In [6]:
d = {"Flour": "4 cups", "Milk": "1 cups"}
d

{'Flour': '4 cups', 'Milk': '1 cups'}

In [8]:
ingredients = pd.Series(d, name = "Dinner")
ingredients

Flour    4 cups
Milk     1 cups
Name: Dinner, dtype: object

In [1]:
import numpy as np

In [55]:
# Задание 35
null_arr = np.zeros((1,4)) # массив из нулей
print("массив из нулей:",null_arr)
arr_10 = np.zeros((1,10))
arr_55 = np.zeros((1,55))
print("одномерные длины 10:", arr_10)
print("одномерные длины 55",arr_55)
# matrix = np.zeros([(1,2,3,4), (5,6,7,8), (9,10,11,12)])
matrix = np.zeros(12).reshape(3,4)
print("матрицу размерами 3 × 4","\n", matrix)
matrix_3d = np.zeros(40).reshape(5, 2, 4)
print("матрицу размерами 2×4×5","\n", matrix_3d)

массив из нулей: [[0. 0. 0. 0.]]
одномерные длины 10: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
одномерные длины 55 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0.]]
матрицу размерами 3 × 4 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
матрицу размерами 2×4×5 
 [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [56]:
null_arr = np.ones((1,4)) # массив из единиц
print("массив из нулей:",null_arr)
arr_10 = np.zeros((1,10))
arr_55 = np.zeros((1,55))
print("одномерные длины 10:", arr_10)
print("одномерные длины 55",arr_55)
# matrix = np.zeros([(1,2,3,4), (5,6,7,8), (9,10,11,12)])
matrix = np.zeros(12).reshape(3,4)
print("матрицу размерами 3 × 4","\n", matrix)
matrix_3d = np.zeros(40).reshape(5, 2, 4)
print("матрицу размерами 2×4×5","\n", matrix_3d)

массив из нулей: [[1. 1. 1. 1.]]
одномерные длины 10: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
одномерные длины 55 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0.]]
матрицу размерами 3 × 4 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
матрицу размерами 2×4×5 
 [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [58]:
null_arr = np.full((1, 5), 9) # массив из 9
print("массив из нулей:",null_arr)
arr_10 = np.zeros((1,10))
arr_55 = np.zeros((1,55))
print("одномерные длины 10:", arr_10)
print("одномерные длины 55",arr_55)
# matrix = np.zeros([(1,2,3,4), (5,6,7,8), (9,10,11,12)])
matrix = np.zeros(12).reshape(3,4)
print("матрицу размерами 3 × 4","\n", matrix)
matrix_3d = np.zeros(40).reshape(5, 2, 4)
print("матрицу размерами 2×4×5","\n", matrix_3d)

массив из нулей: [[9 9 9 9 9]]
одномерные длины 10: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
одномерные длины 55 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0.]]
матрицу размерами 3 × 4 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
матрицу размерами 2×4×5 
 [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [65]:
null_arr = np.full((1, 5), 0.25, dtype=float) # массив из 9
print("массив из нулей:",null_arr)
arr_10 = np.full((1, 10), 0.25, dtype=float)
arr_55 = np.full((1, 55), 0.25, dtype=float)
print("одномерные длины 10:", arr_10)
print("одномерные длины 55",arr_55)
# matrix = np.zeros([(1,2,3,4), (5,6,7,8), (9,10,11,12)])
matrix = np.full((3, 4), 0.25, dtype=float)
print("матрицу размерами 3 × 4","\n", matrix)
matrix_3d = np.full((5, 2, 4), 0.25, dtype=float)
print("матрицу размерами 2×4×5","\n", matrix_3d)

массив из нулей: [[0.25 0.25 0.25 0.25 0.25]]
одномерные длины 10: [[0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25]]
одномерные длины 55 [[0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25
  0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25
  0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25
  0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25]]
матрицу размерами 3 × 4 
 [[0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]]
матрицу размерами 2×4×5 
 [[[0.25 0.25 0.25 0.25]
  [0.25 0.25 0.25 0.25]]

 [[0.25 0.25 0.25 0.25]
  [0.25 0.25 0.25 0.25]]

 [[0.25 0.25 0.25 0.25]
  [0.25 0.25 0.25 0.25]]

 [[0.25 0.25 0.25 0.25]
  [0.25 0.25 0.25 0.25]]

 [[0.25 0.25 0.25 0.25]
  [0.25 0.25 0.25 0.25]]]


In [67]:
arr = np.arange(-10,10,0.1)
arr

array([-1.00000000e+01, -9.90000000e+00, -9.80000000e+00, -9.70000000e+00,
       -9.60000000e+00, -9.50000000e+00, -9.40000000e+00, -9.30000000e+00,
       -9.20000000e+00, -9.10000000e+00, -9.00000000e+00, -8.90000000e+00,
       -8.80000000e+00, -8.70000000e+00, -8.60000000e+00, -8.50000000e+00,
       -8.40000000e+00, -8.30000000e+00, -8.20000000e+00, -8.10000000e+00,
       -8.00000000e+00, -7.90000000e+00, -7.80000000e+00, -7.70000000e+00,
       -7.60000000e+00, -7.50000000e+00, -7.40000000e+00, -7.30000000e+00,
       -7.20000000e+00, -7.10000000e+00, -7.00000000e+00, -6.90000000e+00,
       -6.80000000e+00, -6.70000000e+00, -6.60000000e+00, -6.50000000e+00,
       -6.40000000e+00, -6.30000000e+00, -6.20000000e+00, -6.10000000e+00,
       -6.00000000e+00, -5.90000000e+00, -5.80000000e+00, -5.70000000e+00,
       -5.60000000e+00, -5.50000000e+00, -5.40000000e+00, -5.30000000e+00,
       -5.20000000e+00, -5.10000000e+00, -5.00000000e+00, -4.90000000e+00,
       -4.80000000e+00, -

In [83]:
# Задание 40
arr = np.arange(-np.e,np.e,np.e/50)
arr

array([-2.71828183e+00, -2.66391619e+00, -2.60955056e+00, -2.55518492e+00,
       -2.50081928e+00, -2.44645365e+00, -2.39208801e+00, -2.33772237e+00,
       -2.28335674e+00, -2.22899110e+00, -2.17462546e+00, -2.12025983e+00,
       -2.06589419e+00, -2.01152855e+00, -1.95716292e+00, -1.90279728e+00,
       -1.84843164e+00, -1.79406601e+00, -1.73970037e+00, -1.68533473e+00,
       -1.63096910e+00, -1.57660346e+00, -1.52223782e+00, -1.46787219e+00,
       -1.41350655e+00, -1.35914091e+00, -1.30477528e+00, -1.25040964e+00,
       -1.19604400e+00, -1.14167837e+00, -1.08731273e+00, -1.03294709e+00,
       -9.78581458e-01, -9.24215822e-01, -8.69850185e-01, -8.15484549e-01,
       -7.61118912e-01, -7.06753275e-01, -6.52387639e-01, -5.98022002e-01,
       -5.43656366e-01, -4.89290729e-01, -4.34925093e-01, -3.80559456e-01,
       -3.26193819e-01, -2.71828183e-01, -2.17462546e-01, -1.63096910e-01,
       -1.08731273e-01, -5.43656366e-02, -1.02140518e-14,  5.43656366e-02,
        1.08731273e-01,  

In [88]:
pi_arr = np.arange(-15 * np.pi, 15 * np.pi, np.pi / 12)
pi_arr

array([-4.71238898e+01, -4.68620904e+01, -4.66002910e+01, -4.63384916e+01,
       -4.60766923e+01, -4.58148929e+01, -4.55530935e+01, -4.52912941e+01,
       -4.50294947e+01, -4.47676953e+01, -4.45058959e+01, -4.42440965e+01,
       -4.39822972e+01, -4.37204978e+01, -4.34586984e+01, -4.31968990e+01,
       -4.29350996e+01, -4.26733002e+01, -4.24115008e+01, -4.21497014e+01,
       -4.18879020e+01, -4.16261027e+01, -4.13643033e+01, -4.11025039e+01,
       -4.08407045e+01, -4.05789051e+01, -4.03171057e+01, -4.00553063e+01,
       -3.97935069e+01, -3.95317076e+01, -3.92699082e+01, -3.90081088e+01,
       -3.87463094e+01, -3.84845100e+01, -3.82227106e+01, -3.79609112e+01,
       -3.76991118e+01, -3.74373125e+01, -3.71755131e+01, -3.69137137e+01,
       -3.66519143e+01, -3.63901149e+01, -3.61283155e+01, -3.58665161e+01,
       -3.56047167e+01, -3.53429174e+01, -3.50811180e+01, -3.48193186e+01,
       -3.45575192e+01, -3.42957198e+01, -3.40339204e+01, -3.37721210e+01,
       -3.35103216e+01, -

In [73]:
arr5 = np.eye(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [119]:
arr = np.full((5,5), 0, dtype = float)
for i in range(len(arr)):
    for j in range(len(arr[i])):
        if i == j:
            arr[i,j] = 0.5
arr

array([[0.5, 0. , 0. , 0. , 0. ],
       [0. , 0.5, 0. , 0. , 0. ],
       [0. , 0. , 0.5, 0. , 0. ],
       [0. , 0. , 0. , 0.5, 0. ],
       [0. , 0. , 0. , 0. , 0.5]])

In [120]:
arr = np.full((5,5), 0)
for i in range(len(arr)):
    for j in range(len(arr[i])):
        if i == j:
            arr[i,j] = 1
        else:
            arr[i,j] = 2
arr

array([[1, 2, 2, 2, 2],
       [2, 1, 2, 2, 2],
       [2, 2, 1, 2, 2],
       [2, 2, 2, 1, 2],
       [2, 2, 2, 2, 1]])

In [124]:
# Задание 45
arr = np.full((5,5), 0)
for i in range(len(arr)):
    for j in range(len(arr[i])):
        arr[i,j] = j + 1
arr

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [123]:
arr = np.full((5,5), 0)
for i in range(len(arr)):
    for j in range(len(arr[i])):
        arr[i,j] = i + 1
arr

array([[1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5]])

In [126]:
arr = np.full((5,5), 0)
for i in range(len(arr)):
    for j in range(len(arr[i])):
        if i == j:
            arr[i,j] = 0
        if i > j:
            arr[i,j] = -1
        if i < j:
            arr[i,j] = 1
arr

array([[ 0,  1,  1,  1,  1],
       [-1,  0,  1,  1,  1],
       [-1, -1,  0,  1,  1],
       [-1, -1, -1,  0,  1],
       [-1, -1, -1, -1,  0]])

In [127]:
arr = np.full((5,5), 0)
for i in range(len(arr)):
    for j in range(len(arr[i])):
        if i == j:
            arr[i,j] = 1
        if i > j:
            arr[i,j] = 0
        if i < j:
            arr[i,j] = 2
arr

array([[1, 2, 2, 2, 2],
       [0, 1, 2, 2, 2],
       [0, 0, 1, 2, 2],
       [0, 0, 0, 1, 2],
       [0, 0, 0, 0, 1]])

In [128]:
arr = np.full((5,5), 0)
for i in range(len(arr)):
    for j in range(len(arr[i])):
        if i == j:
            arr[i,j] = 1
        if i > j:
            arr[i,j] = 2
        if i < j:
            arr[i,j] = 0
arr

array([[1, 0, 0, 0, 0],
       [2, 1, 0, 0, 0],
       [2, 2, 1, 0, 0],
       [2, 2, 2, 1, 0],
       [2, 2, 2, 2, 1]])

In [132]:
n = int(input("N: "))
arr = np.full((n,n), 0)
for i in range(len(arr)):
    for j in range(len(arr[i])):
        if i == j:
            arr[i,j] = i + 1 
        if i > j:
            arr[i,j] = i - j + 1
        if i < j:
            arr[i,j] = 0
print(arr)
random.shuffle(arr)
arr

N: 5
[[1 0 0 0 0]
 [2 2 0 0 0]
 [3 2 3 0 0]
 [4 3 2 4 0]
 [5 4 3 2 5]]


array([[5, 4, 3, 2, 5],
       [4, 3, 2, 4, 0],
       [3, 2, 3, 0, 0],
       [2, 2, 0, 0, 0],
       [1, 0, 0, 0, 0]])