In [3]:
import numpy as np
import math as mt
import pandas as pd

In [42]:
alpha=float(input())
s = float(input())
k1=np.sqrt((2*s)/np.tan(mt.radians(alpha)))
k2=np.sqrt((2*s)/np.tan(mt.radians(90-alpha)))
print('Катет b =',k1)
print('Катет a =',k2)
print('Гипотенуза =',np.sqrt((k1**2)+(k2**2)))

45
8
Катет b =  4.0
Катет a =  4.0
Гипотенуза = 5.656854249492381


In [44]:
x=int(input('x='))
y=int(input('y='))
if ((x**3) + (y**3)) <= 9:
    print('Условие истинно')
else:
    print('нет')

x=1
y=1
Условие истинно


In [48]:
x=int(input('x='))
if x%2==0 and x<100:
    print(True)
else:
    print(False)


x=2
True


не хачу

In [51]:
liter = int(input('Бутылок объемом 1 литр: '))
b_ob = int(input('Бутылок большего объема: '))
b_sum = (liter*0.1)+(b_ob*0.25)
print('Cумма, которую можно выручить: {:.2f}$'.format(b_sum))

Бутылок объемом 1 литр: 10
Бутылок большего объема: 5
Cумма, которую можно выручить: 2.25$


In [94]:
summa = int(input('Сумма заказа: '))
nalog = summa*0.2
chai = summa*0.18
print('Налог (20%): {:.2f}'.format(nalog))
print('Чаевые (18%): {:.2f}'.format(chai))
print('Итог:',(summa+nalog+chai))

Сумма заказа: 20000
Налог (20%): 4000.00
Чаевые (18%): 3600.00
Итог: 27600.0


легко

In [58]:
d = float(input('Сумма депозита = '))
for i in range(1,4):
    d=d*1.04
    print('Cумма на счету в конце {}-го года = {:.2f}'.format(i,d))

Сумма депозита = 2500000
Cумма на счету в конце 1-го года = 2600000.00
Cумма на счету в конце 2-го года = 2704000.00
Cумма на счету в конце 3-го года = 2812160.00


легко

In [66]:
chng = int(input('Сдача = '))
c = [100,50,10,5,2,1]
quant = {
        1:0,
        2:0,
        5:0,
        10:0,
        50:0,
        100:0}
s=chng
i=0
while s != 0:
    if s - c[i] >= 0:
        s = s - c[i]
        quant[c[i]]+=1
    else:
        i+=1
print('Номинал монеты/купюры : количество')
print(quant)

Сдача = 191
Номинал монеты/купюры : количество
{1: 1, 2: 0, 5: 0, 10: 4, 50: 1, 100: 1}


In [139]:
sdacha=int(input()) #258 260 453 67
n100=0
n50=0
n10=0
n5=0
n2=0
n1=0
if sdacha//100>0:
    n100=sdacha//100
    if (sdacha-n100*100)//50>0:
        n50=(sdacha-n100*100)//50
        if (sdacha-n100*100-n50*50)//10>0:
            n10=(sdacha-n100*100-n50*50)//10
        else:
            n10=0
            g=sdacha-n100*100-n50*50
            if g//5>0:
                n5=g//5
            else:
                n2=g//2
                n1=g%2
elif sdacha//50>0:
    n50=sdacha//50
    if (sdacha-n50*50)//10>0:
        n10=(sdacha-n50*50)//10
    else:
        n10=0
        h=sdacha-n50*50
        if h//5:
            n5=h//5
        else:
            n2=h//2
            n1=h%2
print('100-рублевых купюр: {}'.format(n100))
print('50-рублевых купюр: {}'.format(n50))
print('10-рублевых монет: {}'.format(n10))
print('5-рублевых монет: {}'.format(n5))
print('2-рублевых монет: {}'.format(n2))
print('1-рублевых монет: {}'.format(n1))

191
100-рублевых купюр: 1
50-рублевых купюр: 1
10-рублевых монет: 4
5-рублевых монет: 0
2-рублевых монет: 0
1-рублевых монет: 0


легшко

оегко

легко(надеюсь)

In [79]:
number = int(input())
nums=str(number)
summ=0
for i in range(4):
    dig = number%10
    summ += dig
    number=number//10
print('{} + {} + {} + {} = {}'.format(nums[0],nums[1],nums[2],nums[3],summ))

3141
3 + 1 + 4 + 1 = 9


In [9]:
c = int(input('Введите количество приобретенных вчерашних буханок хлеба: '))
p = 49
s = p *0.4
r = s*c
print('Цена за буханку: {:.2f}'.format(p), 'Цена со скидкой: {:.2f}'.format(s), 'Общая стоимость приобретенного хлеба: {:.2f}'.format(r), sep = "\n")

Введите количество приобретенных вчерашних буханок хлеба: 10
Цена за буханку: 49.00
Цена со скидкой: 19.60
Общая стоимость приобретенного хлеба: 196.00


легко

In [83]:
d_age = int(input('Введите возраст собаки '))
h_age = 0
if d_age < 0:
    print('Ошибка')
elif d_age > 2:
    h_age = (d_age - 2)*4 + 21
else:
    h_age = d_age*10.5
print('Человеческий возраст собаки: {:.1f}'.format(h_age))

Введите возраст собаки 3
Человеческий возраст собаки: 25.0


In [87]:
letter = input('Введите букву ')
if letter in 'aeiou':
    print('Буква {} - гласная'.format(letter))
elif letter == 'y':
    print('Буква {} может быть как гласной, так и согласной'.format(letter))
else:
    print('Буква {} - согласная'.format(letter))


Введите букву e
Буква e - гласная


с помощью словаря и всё.

легкоооо

In [93]:
poem = 'У Лукоморья дуб зелёный...'
for i in range(len(poem)-1,-1,-1):
    print(poem[i],end='')

...йынёлез буд яьромокуЛ У

In [99]:
s = input('Введите слово ')
i=0
j=len(s)-1
if_pal = False
if s[i]!=s[j]:
    print('Строка не является палиндромом')
else:
    while i < j:
        if s[i] == s[j]:
            if_pal = True
        i+=1
        j-=1
if if_pal == True:
    print('Строка - палиндром')

Введите слово erererg
Строка не является палиндромом


In [101]:
emails_list = ['vasya@mail.ru',
 'akakiy@yandex.ru',
 'spyderman@yandex.ru',
 'XFiles@gmail.com',
 'hello@mail.ru',
 'noname@gmail.com',
 'DonaldTrump@mail.ru',
 'a768#af@yandex.ru',
 'Ivan_Ivanovich@yandex.ru',
 'thebestmail@yandex.ru']

In [119]:
emails_dict={}
for i in emails_list:
    if i.split('@')[1] in emails_dict.keys():
        emails_dict[i.split('@')[1]]+=1
    else:
        emails_dict[i.split('@')[1]]=1
print(emails_dict)

{'mail.ru': 3, 'yandex.ru': 5, 'gmail.com': 2}


In [6]:
emails_list = ['vasya@mail.ru',
'akakiy@yandex.ru',
'spyderman@yandex.ru',
'XFiles@gmail.com',
'hello@mail.ru',
'noname@gmail.com',
'DonaldTrump@mail.ru',
'a768#af@yandex.ru',
'Ivan_Ivanovich@yandex.ru',
'thebestmail@yandex.ru']
emails_dict = {}
for n in emails_list:
    key = n.split("@")
    emails_dict.setdefault(key, 0)
    emails_dict[key] = emails_dict[key] + 1
print(emails_dict)

TypeError: unhashable type: 'list'

In [130]:
string = 'без труда не вытащишь и рыбку из пруда'
words = string.split(' ')
for i in range(len(words)):
    words[i]=words[i].capitalize()
print(*words)

Без Труда Не Вытащишь И Рыбку Из Пруда


In [138]:
string = 'Тяжёлая интернет-зависимость - это когда ты выходишь из интернета, а он из тебя нет.'
komas = ',.:-!?'
for i in string:
    if i in komas:
        string=string.replace(i,':)')
print(string)

Тяжёлая интернет:)зависимость :) это когда ты выходишь из интернета:) а он из тебя нет:)


In [11]:
def replacer(target_str, new_values):
    for i, j in new_values.items():
        target_str = target_str.replace(i, j)
    return target_str

new_values = {".": ":)",
",": ":)",
"!": ":)",
"?": ":)",
"-": ":)",
":": ":)",
";": ":)",
"—": ":)",}
string = "Тяжёлая интернет-зависимость — это когда ты выходишь из интернета, а он из тебя нет."

string = replacer(string, new_values)
print(string)

Тяжёлая интернет:))зависимость :) это когда ты выходишь из интернета:)) а он из тебя нет:))


In [2]:
string = 'саламатсызбы'
new_string = string[::-1]
new_string

'ыбзыстамалас'

In [10]:
def pifa(a,b):
    c=(a**2)+(b**2)
    return round(np.sqrt(c),2)

In [13]:
a=int(input('Первый катет равен: '))
b=int(input('Второй катет равен: '))
print('Длина гипотенузы =', pifa(a,b))


Первый катет равен: 6
Второй катет равен: 8
Длина гипотенузы = 10.0


In [14]:
s=int(input('Расстояние поездки (км): '))
def ride_cost(s):
    return round((((s*1000)//140)*0.25 + 4),2)
print('Стоимость поездки составляет {}$'.format(ride_cost(s)))

Расстояние поездки (км): 1
Стоимость поездки составляет 5.75$


In [6]:
q = int(input('Количество товаров: '))
def del_cost(q):
    if q < 2:
        return q*10.95
    else:
        return 10.95+((q-1)*2.95)
print('Cумма доставки: ',del_cost(q))

Количество товаров: 2
Cумма доставки:  13.899999999999999


In [19]:
nums = ['first','second','third','fourth','fivth','sixth','seventh','eighth','ninth','tenth','eleventh','twelfth']
def number(n):
    if n < 13:
        return nums[n]
    
for i in range(len(nums)):
    print(number(i))

first
second
third
fourth
fivth
sixth
seventh
eighth
ninth
tenth
eleventh
twelfth


In [49]:
months=[31,29,30,31,30,31,30,31,30,31,30,31]
def ordinalDate(d,m,y):
    return d+(sum(months[0:m-1]))

In [51]:
d=int(input('День '))
m=int(input('Месяц '))
y=int(input('Год '))
print('Порядковый номер дня в {} году: {}'.format(y,ordinalDate(d,m,y)))

День 3
Месяц 3
Год 2019
Порядковый номер дня в 2019 году: 63


In [8]:
fr_dict =   {
            'Apples':[30],
            'Bananas':[21],
            'Pineapples':[6]
            }
fruits = pd.DataFrame(fr_dict,columns=(fr_dict.keys()))

In [9]:
fruits


Apples  Bananas  Pineapples
0      30       21           6

In [10]:
fruit_sales = pd.DataFrame({'apples': [35, 41, 47], 'bananas': [21,34,40]}, index=['2017_sales','2018_sales','2019_sales'])


In [11]:
fruit_sales

apples  bananas
2017_sales      35       21
2018_sales      41       34
2019_sales      47       40

In [14]:
ingredients = pd.Series(['4 cups','1 cup','2 large','1 can'],index=['Flour','Milk','Eggs','Spam'],name='Dinner')

In [15]:
ingredients

Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object

In [29]:
n=4

In [81]:
a=[0,1,2,3]
 [0,1,2,3]
 [0,1,2,3]
 [0,1,2,3]

In [82]:
a=np.array(a)

In [83]:
a

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [179]:
b=[]
for i in range(5):
    c=[0 if i==j else 1 if i<j else -1 for j in range(5)]
    b.append(c)
print(b)

[[0, 1, 1, 1, 1], [-1, 0, 1, 1, 1], [-1, -1, 0, 1, 1], [-1, -1, -1, 0, 1], [-1, -1, -1, -1, 0]]


In [45]:
z = np.ones((n,n))
z

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [56]:
for i in range(len(z)):
    for k in range(len(z[i])):
        if i==k:
            z[i,k] = 0
        if i < k:
            z[i,k] = 1
        if i > k:
            z[i,k] = -1

In [57]:
z

array([[ 0.,  1.,  1.,  1.],
       [-1.,  0.,  1.,  1.],
       [-1., -1.,  0.,  1.],
       [-1., -1., -1.,  0.]])

In [69]:
print('массив из нулей')
print(np.zeros((2,2)))
print('одномерные длины 10')
print(np.arange(0,10))
print('одномерные длины 55')
print(np.full((0,55),1))
print('матрицу размерами 3 × 4')
print(np.full((3,4),7))
print('трёхмерный массив формы 2×4×5.')
print(np.zeros((2,4,5)))

массив из нулей
[[0. 0.]
 [0. 0.]]
одномерные длины 10
[0 1 2 3 4 5 6 7 8 9]
одномерные длины 55
[]
матрицу размерами 3 × 4
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
трёхмерный массив формы 2×4×5.
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [70]:
np.arange(-10, 10, 0.1)

array([-1.00000000e+01, -9.90000000e+00, -9.80000000e+00, -9.70000000e+00,
       -9.60000000e+00, -9.50000000e+00, -9.40000000e+00, -9.30000000e+00,
       -9.20000000e+00, -9.10000000e+00, -9.00000000e+00, -8.90000000e+00,
       -8.80000000e+00, -8.70000000e+00, -8.60000000e+00, -8.50000000e+00,
       -8.40000000e+00, -8.30000000e+00, -8.20000000e+00, -8.10000000e+00,
       -8.00000000e+00, -7.90000000e+00, -7.80000000e+00, -7.70000000e+00,
       -7.60000000e+00, -7.50000000e+00, -7.40000000e+00, -7.30000000e+00,
       -7.20000000e+00, -7.10000000e+00, -7.00000000e+00, -6.90000000e+00,
       -6.80000000e+00, -6.70000000e+00, -6.60000000e+00, -6.50000000e+00,
       -6.40000000e+00, -6.30000000e+00, -6.20000000e+00, -6.10000000e+00,
       -6.00000000e+00, -5.90000000e+00, -5.80000000e+00, -5.70000000e+00,
       -5.60000000e+00, -5.50000000e+00, -5.40000000e+00, -5.30000000e+00,
       -5.20000000e+00, -5.10000000e+00, -5.00000000e+00, -4.90000000e+00,
       -4.80000000e+00, -

In [78]:
np.arange(-np.e,np.e, np.e/50)

array([-2.71828183e+00, -2.66391619e+00, -2.60955056e+00, -2.55518492e+00,
       -2.50081928e+00, -2.44645365e+00, -2.39208801e+00, -2.33772237e+00,
       -2.28335674e+00, -2.22899110e+00, -2.17462546e+00, -2.12025983e+00,
       -2.06589419e+00, -2.01152855e+00, -1.95716292e+00, -1.90279728e+00,
       -1.84843164e+00, -1.79406601e+00, -1.73970037e+00, -1.68533473e+00,
       -1.63096910e+00, -1.57660346e+00, -1.52223782e+00, -1.46787219e+00,
       -1.41350655e+00, -1.35914091e+00, -1.30477528e+00, -1.25040964e+00,
       -1.19604400e+00, -1.14167837e+00, -1.08731273e+00, -1.03294709e+00,
       -9.78581458e-01, -9.24215822e-01, -8.69850185e-01, -8.15484549e-01,
       -7.61118912e-01, -7.06753275e-01, -6.52387639e-01, -5.98022002e-01,
       -5.43656366e-01, -4.89290729e-01, -4.34925093e-01, -3.80559456e-01,
       -3.26193819e-01, -2.71828183e-01, -2.17462546e-01, -1.63096910e-01,
       -1.08731273e-01, -5.43656366e-02, -1.02140518e-14,  5.43656366e-02,
        1.08731273e-01,  

In [79]:
np.arange(-15*np.pi, 15*np.pi, np.pi/12)

array([-4.71238898e+01, -4.68620904e+01, -4.66002910e+01, -4.63384916e+01,
       -4.60766923e+01, -4.58148929e+01, -4.55530935e+01, -4.52912941e+01,
       -4.50294947e+01, -4.47676953e+01, -4.45058959e+01, -4.42440965e+01,
       -4.39822972e+01, -4.37204978e+01, -4.34586984e+01, -4.31968990e+01,
       -4.29350996e+01, -4.26733002e+01, -4.24115008e+01, -4.21497014e+01,
       -4.18879020e+01, -4.16261027e+01, -4.13643033e+01, -4.11025039e+01,
       -4.08407045e+01, -4.05789051e+01, -4.03171057e+01, -4.00553063e+01,
       -3.97935069e+01, -3.95317076e+01, -3.92699082e+01, -3.90081088e+01,
       -3.87463094e+01, -3.84845100e+01, -3.82227106e+01, -3.79609112e+01,
       -3.76991118e+01, -3.74373125e+01, -3.71755131e+01, -3.69137137e+01,
       -3.66519143e+01, -3.63901149e+01, -3.61283155e+01, -3.58665161e+01,
       -3.56047167e+01, -3.53429174e+01, -3.50811180e+01, -3.48193186e+01,
       -3.45575192e+01, -3.42957198e+01, -3.40339204e+01, -3.37721210e+01,
       -3.35103216e+01, -

In [87]:
n5=np.ones((5, 5))
n5

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [88]:
d=[0.5 for i in range(5)]
np.fill_diagonal(n5,d)

In [89]:
n5

array([[0.5, 1. , 1. , 1. , 1. ],
       [1. , 0.5, 1. , 1. , 1. ],
       [1. , 1. , 0.5, 1. , 1. ],
       [1. , 1. , 1. , 0.5, 1. ],
       [1. , 1. , 1. , 1. , 0.5]])

In [90]:
f=np.full((5,5),2)
ones=np.ones(5)
np.fill_diagonal(f,ones)

In [91]:
f

array([[1, 2, 2, 2, 2],
       [2, 1, 2, 2, 2],
       [2, 2, 1, 2, 2],
       [2, 2, 2, 1, 2],
       [2, 2, 2, 2, 1]])

In [155]:
g=np.ones((5, 5))
g[0,0:]=2
g[1,0:]=2

g

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [146]:
j=np.ones((5, 5))
for i in range(0,len(j[0])):
    j[0:,i]=i+1

In [147]:
j

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

In [157]:
y=np.ones((5, 5))
for i in range(0,len(y[0])):
    y[i,:]=i+1
y

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [159]:
b=[]
for i in range(5):
    c=[1 if i==j else 0 if i<j else 2 for j in range(5)]
    b.append(c)
np.array(b)

array([[1, 0, 0, 0, 0],
       [2, 1, 0, 0, 0],
       [2, 2, 1, 0, 0],
       [2, 2, 2, 1, 0],
       [2, 2, 2, 2, 1]])

In [ ]:
for i in range(len(z)):
    for k in range(len(z[i])):
        if i==k:
            z[i,k] = 0
        if i < k:
            z[i,k] = 1
        if i > k:
            z[i,k] = -1

In [ ]:
[[0,1,2,3]
[0,1,2,3]
[0,1,2,3]
[0,1,2,3]]

In [161]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [225]:
p=[1,1,1,1,1]

In [226]:
p=np.diagflat(p, k=-1)
np.fill_diagonal(p,1)
print(p)

[[1 0 0 0 0 0]
 [1 1 0 0 0 0]
 [0 1 1 0 0 0]
 [0 0 1 1 0 0]
 [0 0 0 1 1 0]
 [0 0 0 0 1 1]]


In [223]:
v=p
np.random.shuffle(v)
v

array([[1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 1],
       [1, 1, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0],
       [0, 0, 0, 1, 1, 0],
       [0, 1, 1, 0, 0, 0]])

In [221]:
v

In [207]:
k=np.zeros((5,5))
for i in range(len(k)):
    for j in range(len(k[i])):
        if i==j:
            k[i,j]=1

In [208]:
k

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [205]:
n=int(input())
l=[    [0, 1, 2, 3,4],
       [0, 1, 2, 3,4],
       [0, 1, 2, 3,4],
       [0, 1, 2, 3,4],
       [0, 1, 2, 3,4]]
for i in range(n):
    for j in range(n):
        if i==j:
            if i%2==0:
                l[i][j]='_'
            else:
                l[i][j]='|'
        else:
            l[i][j]=0
print(np.array(l))

5
[['_' '0' '0' '0' '0']
 ['0' '|' '0' '0' '0']
 ['0' '0' '_' '0' '0']
 ['0' '0' '0' '|' '0']
 ['0' '0' '0' '0' '_']]
